### ISSUE TITLE
Missing environment variable in GitLab CI

### ISSUE THREAD

**Issue by TimothyEarley** [jgitver/jgitver-maven-plugin#118]
## Issue

**version**: 1.5.1

**usage context**:

- [X] maven command line: 3.3.9

**Problem description**:

When trying to deploy a project with the jGitVer maven plugin through the GitLab CI pipeline the necessary environment variable (CI_PROJECT_ID) is not applied to the pom. I wouldn't have suspected this plugin as the cause, but commenting out the extension in `.mvn/extensions.xml` fixes the issue with otherwise the same setup.

The error message (see below) would indicate that the env variable is not set in the pom but from my testing, it is set in the runner so somewhere it must be getting lost.

Pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0</version>
	<packaging>jar</packaging>

	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<repositories>
		<repository>
			<id>gitlab-maven</id>
			<url>https://[our gitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
		</repository>
	</repositories>
	<distributionManagement>
		<repository>
			<id>gitlab-maven</id>
			<url>https://[our gitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
		</repository>
		<snapshotRepository>
			<id>gitlab-maven</id>
			<url>https://[our gitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
		</snapshotRepository>
	</distributionManagement>


	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<scm>
		<developerConnection>scm:git:git@[our gitlab]/test-project.git</developerConnection>
		<tag>HEAD</tag>
	</scm>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

Gitlab ci defiition (.gitlab-ci.yml, default maven template)
```
# This file is a template, and might need editing before it works on your project.
# This file is a template, and might need editing before it works on your project.

# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

# This template will build and test your projects
# * Caches downloaded dependencies and plugins between invocation.
# * Verify but don't deploy merge requests.
# * Deploy built artifacts from master branch only.

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# This template uses jdk8 for verifying and deploying images
image: maven:3.3.9-jdk-8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

# For merge requests do not `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master

# Verify merge requests using JDK8
verify:jdk8:
  <<: *verify

# To deploy packages from CI, create a ci_settings.xml file
# For deploying packages to GitLab's Maven Repository: See https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for more details.
# Please note: The GitLab Maven Repository is currently only available in GitLab Premium / Ultimate.
# For `master` branch run `mvn deploy` automatically.
deploy:jdk8:
  stage: deploy
  script:
    - if [ ! -f ci_settings.xml ];
        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml'
  only:
    - master

```

Output from GitLab runner:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.2.8-arch1-1-arch", arch: "amd64", family: "unix"
3528 [INFO] Error stacktraces are turned on.
3544 [INFO] No suitable configuration file found, using defaults
3630 [INFO] Using jgitver-maven-plugin [1.5.1] (sha1: e45d1669b39cedb98720dd33cc14d0185b455ca1)
4012 [INFO]     version '0.0.3-SNAPSHOT' computed in 382 ms
4012 [INFO] 
4019 [INFO] Scanning for projects...
4089 [WARNING] Could not transfer metadata org.springframework.boot:spring-boot-dependencies:0.0.3-SNAPSHOT/maven-metadata.xml from/to gitlab-maven (https://[ourgitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven): Illegal character in path at index 44: https://[ourgitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven/org/springframework/boot/spring-boot-dependencies/0.0.3-SNAPSHOT/maven-metadata.xml
4094 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.boot:spring-boot-starter-parent:[unknown-version]: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:0.0.3-SNAPSHOT from/to gitlab-maven (https://[ourgitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven): Illegal character in path at index 44: https://[ourgitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven/org/springframework/boot/spring-boot-dependencies/0.0.3-SNAPSHOT/spring-boot-dependencies-0.0.3-SNAPSHOT.pom @ org.springframework.boot:spring-boot-starter-parent:[unknown-version], /builds/timothymark.earley/test-project/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.0.1.RELEASE/spring-boot-starter-parent-2.0.1.RELEASE.pom, line 3, column 13

...


Caused by: java.net.URISyntaxException: Illegal character in path at index 44: https://[our gitlab]/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven/org/springframework/boot/spring-boot-dependencies/0.0.3-SNAPSHOT/spring-boot-dependencies-0.0.3-SNAPSHOT.pom


```
